### ISSUE TITLE
Able to install Versions but Unable to launch after first launch

### ISSUE THREAD

**Issue by CouncilmenGhost** [RiskiVR/BSLegacyLauncher#10]
I was able to install 1.16.2 using the app, all was well until I closed Beat Saber and reopened the Beat Saber Legacy app. I wasn't able to see any launch options or able to launch. "Beat Saber not Installed" message popped up when I tried to launch. I couldn't install a new version because it wouldn't go to the download prompt.

**Comment by RiskiVR** [comment]
did you extract the launcher before running it?
