### ISSUE TITLE
invalid password

### ISSUE THREAD

**Issue by Vainstains** [RiskiVR/BSLegacyLauncher#13]
i keep entering my password, even changed it 3 times and it keeps denying it

**Comment by RiskiVR** [comment]
are you sure you are using your username to log in, and not your Display name?

**Comment by UrkiMimi** [comment]
Also try using the password reveal feature it might be pretty helpful for this situation
![image](https://user-images.githubusercontent.com/74517821/127723089-d2e19811-b18e-4578-a30b-fa89f5f5d180.png)

**Comment by Vainstains** [comment]
I didn't know there was a display name, I just use my steam username and password with both hide boxes unticked. I've double checked my password. I also noticed that for a split second before it says that it reads "an unknown error has occurred"

**Comment by JinstoNim** [comment]
You see the area with your name and your profile next to each other, the one that has a dropdown that allows you to log out? Go there, and see what name is listed beside "Log out of account: ____". Use that name in it.

**Comment by Vainstains** [comment]
what do you mean? in the app or steam

**Comment by RiskiVR** [comment]
steam. your username should be located where the red is: 

![image](https://user-images.githubusercontent.com/40964931/127726503-06cebdbe-7635-46f7-a8d8-a08eeab5b64e.png)
