### ISSUE TITLE
Purchased DLC songs won't play

### ISSUE THREAD

**Issue by StrongerThantheBoys** [RiskiVR/BSLegacyLauncher#14]
None of the DLC songs I actually purchased through Steam will play (Counting Stars, etc.). I just get an "error loading" message.

I'm using legacy Beat Saber 1.16.2. with the BSLegacyLauncher.

![20210731193118_1](https://user-images.githubusercontent.com/87719955/127756333-b7b77515-8746-4e26-9e14-efcfbed011fc.jpg)

**Comment by RiskiVR** [comment]
Did you copy over the DLC folder?

**Comment by UrkiMimi** [comment]
First of all DLCs will download on older versions, but Beat Saber creates a DLC folder in the root directory of your steam install. This is not a launcher issue rather an actual Beat Saber issue. Please do not misuse the issues tab with actual Beat Saber issues.
![image](https://user-images.githubusercontent.com/74517821/127756448-d9e8f55c-07ad-40fe-9f21-1bb426474cdc.png)

**Comment by UrkiMimi** [comment]
For further issues with your problem please go to #PC-Support on the discord server. If you do not see it, go to #get-roles
