### ISSUE TITLE
[Feature Request] Feature for multiple installs in a carousel like interface similar to Front Row on OS X 10.4

### ISSUE THREAD

**Issue by UrkiMimi** [RiskiVR/BSLegacyLauncher#15]
I know this was a heavily requested feature outside of Github but I'll make a new comment once I get done with my UI concepts

Below is the front row interface

![image](https://user-images.githubusercontent.com/74517821/128608965-dfebb33f-8a5c-4e6e-b9c8-cecebe82f8ac.png)

**Comment by RiskiVR** [comment]
Install switching is planned, I just don't have a proper UI for it yet. I'm not gonna use MacOS style stuff as this is my own UI and I'm gonna focus on that. 

I also don't have detection for what's installed, so I'll need to figure out how to do that properly.

**Comment by UrkiMimi** [comment]
aight ty

**Comment by RiskiVR** [comment]
Added in v1.5.0
