### ISSUE TITLE
[Recommendation] Please use BSIPA 3 cause BSIPA 4 causes issues with beta versions

### ISSUE THREAD

**Issue by UrkiMimi** [RiskiVR/BSLegacyLauncher#16]
Yeah while helping someone out I found out the Install BSIPA installs BSIPA 4 instead of BSIPA 3 which can cause issues

**Comment by RiskiVR** [comment]
BSIPA 4 will be replaced with BSIPA 3 in the next update

**Comment by UrkiMimi** [comment]
haha ill close issue
