### ISSUE TITLE
Rare case of being unable to authenticate with Steam

### ISSUE THREAD

**Issue by RiskiVR** [RiskiVR/BSLegacyLauncher#19]
There's a very rare case of logging into Steam with the Launcher, and after a few successful logins, it tells you "Incorrect Password" even if the info is correct. I've had this happen to me as well.

Edit 12/17/21: Temporary fix has been found. Add a capital letter to your username input. Idk why it works but it does. This will be further looked at!

![image](https://user-images.githubusercontent.com/40964931/132113410-bbceb748-23c9-4806-97a8-4b8b8abc9198.png)

**Comment by Oikio** [comment]
Same problem here, nothing helps (changing ip, reinstalling launcher, changing password).

**Comment by YorVeX** [comment]
Same problem with v1.3.3 right now. It has worked fine in the past, now I updated BSLegacyLauncher to v1.3.3 from the previous version and also wanted to download a newer BS version, but can't login even after multiple attempts. steamstat.us doesn't report any issues with steam and login to standard Steam client works without issues.

`[05:27:27.489][Assembly-CSharp][Info] - Successfully connected to Steam3 service!
[05:27:27.922][Assembly-CSharp][Info] - Unable to login to Steam3: InvalidPassword
[05:27:27.923][Assembly-CSharp][Error] - Connection Failed! RESP: Unable to login to Steam3: InvalidPassword
[05:27:27.923][Assembly-CSharp][Info] - Disconnected from Steam
[05:27:27.923][Assembly-CSharp][Info] - Unable to get steam3 credentials.`

**Comment by In4init3** [comment]
same issue, i dont seem a fix is near, posted on the discord for any help

**Comment by JohSchillerEmnify** [comment]
Same issue, if i can be of any help let me know. 
Update: Tried changing my password, doesn't work. 
Update2: For now using the cli (BSLecacyUtil) works, not sure what the difference to this one is.

**Comment by RiskiVR** [comment]
A temporary fix has been found! Simply capitalize the first letter in your username if you get this issue. I have no idea why but it works.

**Comment by Nicklaw434** [comment]
I'm having this issue and I've tried a lot of things so far that haven't worked. I've tried to capitalize the first letter in my username, I've tried using all of my previous and current usernames, I've even tried turning off steam guard. I had this problem 5 or so months ago and I thought that when I came back it would be miraculously fixed but unfortunately enough for me this problem is still occurring and I haven't been able to get on the launcher. If anyone could find a fix or at least give me some ideas, that would be greatly appreciated!

**Comment by RiskiVR** [comment]
@Nicklaw434 First of all, DON'T disable Steam Guard. It's **very** important that your account is secure. Without Steam Guard, your account is very vulnerable. It also won't work with the Launcher if it's disabled.

As far as your issue goes, just add another capital letter to your username. Example, if "Name" doesn't work, then do "NAme".
I know it's weird, I couldn't figure out why it does that either. Just do that and you'll be good.

**Comment by VCNinc** [comment]
Seems like some kind of caching issue! (I am running out of capital letters!)

**Comment by CANA-Dan** [comment]
got this issue too. my name is a string of numbers tho so i cant just put capitals instead

**Comment by In4init3** [comment]
thanks the temp fix works for me

**Comment by RiskiVR** [comment]
Fixed in v1.4.0
