### ISSUE TITLE
Stuck on RAR unpack

### ISSUE THREAD

**Issue by StrongerThantheBoys** [RiskiVR/BSLegacyLauncher#20]
The RAR unpack gets stuck halfway and doesn't move any further. Tried both downloading and opening RAR from Downloads folder as well as using Open File with RAR Opener directly from the GitHub site.

![update stuck](https://user-images.githubusercontent.com/87719955/132133158-afa633d9-6edb-4952-9a26-52b5d3835aa7.jpg)

When I click Cancel, I get the following error message:
![error](https://user-images.githubusercontent.com/87719955/132133935-9300be13-3e61-423f-8636-e5949c37b61e.jpg)

I have plenty of space (185GB) on my hard drive.

**Comment by UrkiMimi** [comment]
Please use 7zip or WinRAR and DO NOT use software that is from the Microsoft Store.
