### ISSUE TITLE
[Feature Request] Add "move to Steam directory" to GUI launcher

### ISSUE THREAD

**Issue by androng** [RiskiVR/BSLegacyLauncher#22]
The v1.3.2 launcher seems to be missing the option to move the Beat Saber files to the Steam directory. This is important to me because somewhere in my Steam directory there is a JSON file that contains all my SongPlayHistory data. Yes I could move the JSON file to the downgraded Beat Saber folder but now I have multiple copies of that file I have to remember to move. 

Related: I launched Beat Saber v1.17.0, clicked "Launch" in the v1.3.2 GUI, and the game says "Error Loading Data" when clicking on any song. Adding this feature may fix this issue as well. 

![20210726215223_1](https://user-images.githubusercontent.com/605932/134472105-e18da77a-2fcd-4a6a-a915-c00686b71c50.jpg)

**Comment by RiskiVR** [comment]
The launcher has never had the ability to move the install to Steam due to it being updated by Steam, which is why the feature has been removed from the console utility as well.
