### ISSUE TITLE
[Feature request] Alternate ways for Steam login

### ISSUE THREAD

**Issue by MtKrRa** [RiskiVR/BSLegacyLauncher#24]
Is it possible to log in by using browser cookies? Or some certificates saved by the Steam client locally? I'm a new user and I'm not very familiar will the details, so I don't know if it's even possible or not. I just think a lot more people would like to try the app if it has other ways to sign in.

Anyway, thanks a lot for the easy-to-use app.

**Comment by RiskiVR** [comment]
You're welcome! However, it is not possible to authenticate with Depotdownloader, so I'm sorry but there is no other way.

**Comment by MtKrRa** [comment]
> 
> 
> You're welcome! However, it is not possible to authenticate with Depotdownloader, so I'm sorry but there is no other way.

Thank you for your prompt reply! I did a bit more research after this and found:
https://github.com/fifty-six/zig.SteamManifestPatcher
A simple program that modifies the Steam built-in downloader and allows users to manually downgrade games using the Steam console. (at least that's my understanding of it)

Is it possible to utilize the same method in BSLegacy (keep the UI, but patch the Steam in the background, and auto type in some console command, and move around the files) so that we don't have to sign in at all?

I understand this will cost more time in development and I would totally understand if you feel unnecessary to implement a method like this. This is just a suggestion.

Thank you a lot anyways.

**Comment by RiskiVR** [comment]
Doing that would take away the whole point of the launcher, having it's own dedicated install.
