### ISSUE TITLE
Storing encrypted credentials

### ISSUE THREAD

**Issue by char-ptr** [RiskiVR/BSLegacyLauncher#25]
i have briefly viewed over the source code and i see that you guys store the steam login credentials in plain text, i think it would be a good idea to encrypt them to prevent people getting compromised from using this application.

**Comment by LlysiX** [comment]
This vulnerability has been patched, credentials are no longer being saved.

**Comment by RiskiVR** [comment]
Steam login password is no longer locally stored for security reasons.
