### ISSUE TITLE
Game and downloading not working after closing launcher

### ISSUE THREAD

**Issue by hh33yy** [RiskiVR/BSLegacyLauncher#28]
So essentially when I first download the launcher, open it, I can download and open the Beat Saber version. But once I close the launcher and open it again I cant open the game saying it isnt installed, and I cant install anything else either. The only fix is to reinstall the launcher everytime I close it. I was /this\ close to an easy downgrade lol.

**Comment by RiskiVR** [comment]
Did you extract the Launcher?
