### ISSUE TITLE
Can no longer see Launch Options

### ISSUE THREAD

**Issue by abhaycashikar** [RiskiVR/BSLegacyLauncher#29]
Just upgraded my BSLegacyLauncher to the latest Version 1.3.7, and can no longer see any launch options. See attached screenshot:
![image](https://user-images.githubusercontent.com/43579092/156381337-d3d42983-9baa-4bcb-a805-f9fa91234b0d.png)

I would ideally like to run the game in Oculus Mode to reduce input latency, among other things. Is there any way to do this still? Thank you!

**Comment by RiskiVR** [comment]
Check to see if your installed version of Beat Saber isn't incomplete

**Comment by abhaycashikar** [comment]
I am able to play the game normally using BSLL, I just can't enable the
Oculus mode from within the app anymore.

**Comment by RiskiVR** [comment]
You may be missing the BeatSaberVersion.txt file, This may cause the Launch Options to go missing.
To resolve this issue, add a new txt file, name it BeatSaberVersion.txt, and enter the Beat Saber version inside.

**Comment by RiskiVR** [comment]
Actually wait, you might be missing a BeatSaberVersion.txt file, usually that causes Launch Options to go missing.
