### ISSUE TITLE
Select Version button is disabled when an empty Beat Saber folder is created

### ISSUE THREAD

**Issue by ddakebono** [RiskiVR/BSLegacyLauncher#3]
When a problem occurs during the DepotDownloader step and the Beat Saber folder has already been generated the Select Version button will be disabled.

This stops users from reinstalling as the Uninstall button is not activated either.

Quick Fix: Delete the generated Beat Saber folder in the launcher's directory

**Comment by RiskiVR** [comment]
Fixed in v1.1.0
