### ISSUE TITLE
Game does not launch graded version, uses most recent Steam version instead, then closes itself

### ISSUE THREAD

**Issue by CommonStarguy** [RiskiVR/BSLegacyLauncher#30]
Trying to roll back to 1.19.1 for modding, but when I launch through the Legacy Launcher no mods appear to be loaded. I suspect it's getting confused and launching 1.20.0 (the latest official version as of this post), but I have no way to tell for sure and it doesn't provide any logs. I've uninstalled and reinstalled, checked the directories, disabled and restarted steam, but nothing seems to change.

**Comment by RiskiVR** [comment]
If no mods are loading, try opening the game first before modding it. if you continue to have further issues with modding, this is an issue with modassistant. 

If the game is instantly closing on launch, make sure steam is open, then try again.
