### ISSUE TITLE
[Feature Request] Symlink relative path instead of absolute path

### ISSUE THREAD

**Issue by error7404** [RiskiVR/BSLegacyLauncher#34]
Symlink as relative path for better portability
---

from:
<img src="https://user-images.githubusercontent.com/84022019/172717164-72e4ffe5-cb58-457a-951c-623348b520e0.png" alt="absolute path" height="80"/>
to:
<img src="https://user-images.githubusercontent.com/84022019/172717442-1b9d1fcc-81ac-43e1-9566-e305369ccaf1.png" alt="relative path" height="80"/>

**Comment by RiskiVR** [comment]
The launcher directs to it's own local paths, so I'm unsure what this would change.

**Comment by error7404** [comment]
If you want to move the folder or copy it to a different drive.
But it would not change anything for the user.

**Comment by RiskiVR** [comment]
Moving the launcher folder doesn't affect the symlinked folders

**Comment by ComputerElite** [comment]
Yes it does, the launcher used absolute paths for everything, including symlinks. As they are written to disk they don't change when you move the launcher. If the create symlinks button is pressed again they get updated to the new folder
