### ISSUE TITLE
[Suggestion] Update Unity Version

### ISSUE THREAD

**Issue by UrkiMimi** [RiskiVR/BSLegacyLauncher#36]
Hey Risk, I know we haven't talked in a while but I honestly think updating the project database of BSLL might be a good idea as it allows for you to use the new tools and get rid of deprecated stuff.

Urki Mii <3

**Comment by RiskiVR** [comment]
It isn't as easy as it sounds to migrate unity versions. I'm also unable to contact you in Discord for further discussions.
