### ISSUE TITLE
ScoreSaber not authenticating after launcher update

### ISSUE THREAD

**Issue by FistyDotMe** [RiskiVR/BSLegacyLauncher#40]
I just updated the BS legacy launcher from 1.3.7 to the newest 1.5.4 version. But now Score Saber won't authenticate even after restarting Launcher, Steam, Pc. Was working fine yesterday.

**Comment by UrkiMimi** [comment]
<img width="688" alt="Screen Shot 2022-08-12 at 11 44 26 AM" src="https://user-images.githubusercontent.com/74517821/184405180-5332c5eb-d912-4792-86e5-ec7a0f35174a.png">
I'm just gonna leave this here

**Comment by UrkiMimi** [comment]
Also I am pretty sure the ss api has nothing to do with BSLL

**Comment by RiskiVR** [comment]
Exactly what Urki said.
