### ISSUE TITLE
Using -fpfc may not disable SteamVR depending on steam's install folder

### ISSUE THREAD

**Issue by quiltedhills** [RiskiVR/BSLegacyLauncher#42]
Somewhat of an obscure bug, but having the steam's core folder installed somewhere other than `C:\Program Files (x86)` (it's just `C:\steam` in my case, honestly not sure why) means that BSLL can't find SteamVR nor prevent it from launching. Maybe it could be possible to manually set the location of the SteamVR folder in advanced settings?

**Comment by RiskiVR** [comment]
Not sure why you would want your Steam location installed somewhere that isn't on your C:/ drive. If space is what you're worried about, that's what Steam Library folders are for.

**Comment by MintLily** [comment]
I have Beat Saber on a second drive (D:\) And BSLL works just fine for me. C:\ is protected by windows, whereas C:\Program Files is less protected. Try changing your Steam library location to the default `C:\Program Files (x86)\Steam` the full game path will then become `C:\Program Files (x86)\Steam\steamapps\common\Beat Saber`

**Comment by MintLily** [comment]
Also going off on the title alone, this sounds like a Steam issue, not an us issue. But that's just my forethought.

**Comment by quiltedhills** [comment]
sorry for a bit of a delayed response. As I said - this **is** that kind of bug that other people may very rarely, if at all, encounter. So I just wanted your thoughts on if this needs addressing from BSLL's side, you know, just in case. Seems like it doesn't (because, well, you can just change steam's install folder) and that's completely fine. Thanks for taking your time to respond and have a good day <3
