### ISSUE TITLE
BSLegacy crashing when click on install mods

### ISSUE THREAD

**Issue by Need2rev** [RiskiVR/BSLegacyLauncher#43]
i installed legacy ipa while selecting version 0.11.2 and when u click install mods its crashing and the modmanager zip folder is corrupted

**Comment by RiskiVR** [comment]
Please do not use the Install Mods button as it will be a depreciated feature in the future. 
For 0.11.2 mods and others, please visit our plugins page: https://bslegacy.com/plugins
