### ISSUE TITLE
Beatsaber not installed

### ISSUE THREAD

**Issue by jango-bob** [RiskiVR/BSLegacyLauncher#45]
I'm unable to click versions already installed and KNOW they are installed in the correct places. i cannot select any versions and nothing launches despite being able to launch beatsaber elsewhere eg: steam.

and yes i've set it up properly and extracted it.

**Comment by RiskiVR** [comment]
There was a silent patch yesterday. Please redownload the launcher and try again.

**Comment by jango-bob** [comment]
i did already, i replaced the launcher entirely, still nothing

**Comment by RiskiVR** [comment]
please provide screenshots.

**Comment by jango-bob** [comment]
i fixed it by deleting the installed versions folder and then installing it again. please fix this, i had to reinstall all mods and everything again.

**Comment by RiskiVR** [comment]
I'm not sure what needs to be fixed, since you haven't provided any evidence of this issue.

**Comment by paveldvorak5** [comment]
Safe thing here. My BS is not installed on C: drive
