### ISSUE TITLE
Download Percentage Wrong

### ISSUE THREAD

**Issue by GERJanB** [RiskiVR/BSLegacyLauncher#46]
![image](https://user-images.githubusercontent.com/80533534/222242361-2c507847-2ab4-471e-87c1-b0fa89c738f2.png)

As displayed in the image the Download percentage is displayed wrong. It shows Values even above 1000%.

The effected Version is 1.7.1

**Comment by RiskiVR** [comment]
Works on my machine
![image](https://user-images.githubusercontent.com/40964931/222243276-dd936f93-a252-47cd-91ec-2e532170c5f6.png)

**Comment by ComputerElite** [comment]
Which OS are you running?

**Comment by ComputerElite** [comment]
Oh and more importantly, may I know what language your computer is set to

**Comment by GERJanB** [comment]
I am running Windows 10 and the language of my OS is set to English (US).

But i have changed Time and Currency Display to the German Style. I also changed the Seperators within Numbers. So for me Numbers are not displayed like this: 10,000.54      They are displayed like this 10.000,54. 

Maybe that has something to do with it. By the End of the Download it displayed somewhere around 12000%

**Comment by ComputerElite** [comment]
Yeah it most likely has. I pushed something that should fix it. Expect the fix in the next update

**Comment by RiskiVR** [comment]
Fixed in v1.7.2
