### ISSUE TITLE
Feature Request: Discussion tab in github repo for people who have non-bug issues

### ISSUE THREAD

**Issue by JpTiger** [RiskiVR/BSLegacyLauncher#47]
I thought  it might be a good idea to open [the discussion feature in Github](https://github.com/features/discussions) for this for folks like me who are having technical issues that lie somewhere between the monitors and the backs of our chairs. I'm not getting this to work the way that I want to but I'm 99.9% certain it's because I'm not using it correctly rather than any fault of the software. It'd be helpful to have a place to post that both to get a solution for myself and for others who have similar problems. Thank you!

**Comment by RiskiVR** [comment]
Discussions have been enabled on this repository. Thank you for the suggestion.
