### ISSUE TITLE
Launching beat saber from BSLL doesn't work

### ISSUE THREAD

**Issue by ceRo9307** [RiskiVR/BSLegacyLauncher#49]
When i try to launch beat saber with the BSLL it doesnt start the game, it just launches the game and then closes it without giving me anything to work with, at first i had another problem with the mono and fixed that issue but now its broken

**Comment by MintLily** [comment]
Make sure you have Steam(VR) running. And also **not** running as admin.

**Comment by RiskiVR** [comment]
Actual Steam client*

**Comment by ceRo9307** [comment]
i looked closer into the files and it says game does not have a unity project so its a problem on my side
