### ISSUE TITLE
net 6.0

### ISSUE THREAD

**Issue by FurrySabrina** [RiskiVR/BSLegacyLauncher#54]
Sorry to interupt anything, but I have a friend that has issues with the BSL and everytime he has to download the 1.28.0 update, the thing keeps saying to install net 6.0 **even though** the "site" does not work (we even checked that it was installed properly and it was)  And adding on to that, when we manually install net, the thing keeps giving the error.

If anyone on the other side of the screen can help, please do.

![image_2023-06-30_024740213](https://github.com/RiskiVR/BSLegacyLauncher/assets/132963689/21d96c82-500e-4445-8b9c-3487e46e6d72)

**Comment by RiskiVR** [comment]
You can install .NET 6 from Microsoft's official page: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.408-windows-x64-installer

**Comment by FurrySabrina** [comment]
it still wont work tho

**Comment by FurrySabrina** [comment]
that is what im saying
