### ISSUE TITLE
.NET Download Redirect Link Broken

### ISSUE THREAD

**Issue by ISolox** [RiskiVR/BSLegacyLauncher#59]
Most likely caused by the stuff going on with the website as of 7/28/23.

When signing in with steam when you don't have .NET 6.0 installed, the link it brings you to is dead.

Broken Link:
https://link.bslegacy.com/dotnet6

**Comment by RiskiVR** [comment]
This is known, please use the official download for .NET 6 here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.408-windows-x64-installer
