### ISSUE TITLE
Launcher getting smaller making it unusable  

### ISSUE THREAD

**Issue by Donovan998** [RiskiVR/BSLegacyLauncher#6]
Each time I open and close the launcher it get smaller with no way of maximizing it or bring it back to original size even after a couple fresh installs of the launcher. Worked fine for a wile but it is too small to make out any of the text making it not usable for me. Making screen resolution similar to the launcher still has the text unreadable.  

![IMG_5690](https://user-images.githubusercontent.com/85034509/120080795-75d65c80-c088-11eb-882e-dcd1323063a9.jpg)
![so small](https://user-images.githubusercontent.com/85034509/120080810-81c21e80-c088-11eb-97ab-f4fb03376fe7.png)

**Comment by RiskiVR** [comment]
An update was pushed today. I've added some code to set resolution properly. Try it out

**Comment by Donovan998** [comment]
> An update was pushed today. I've added some code to set resolution properly. Try it out

Works good thanks for the update

**Comment by RiskiVR** [comment]
no problem!
