### ISSUE TITLE
Bought DLC on beat saber not showing up in legacy beat saber

### ISSUE THREAD

**Issue by CutieAshlynn** [RiskiVR/BSLegacyLauncher#65]
When i load up legacy beat saber it shows only a few of my bought DLC maps and they are playable but, a ton of my other maps that i bought are showing Error load data.

How could i fix this?
or is there gonna be a fix to this soon.

**Comment by RiskiVR** [comment]
Hi!

Copy the DLC Folder from your Steam install to your BSLegacy install, and they should be accessible!

**Comment by CutieAshlynn** [comment]
i did that but, thats what caused this issue where i can only play a few and the others have error loading data

**Comment by CutieAshlynn** [comment]
so all my panic at the disco and imagine dragons songs are saying error loading data
and they are in the dlc folder i copied

**Comment by Gamer101233** [comment]
seems to be a major bug with the legacy beat saber

**Comment by ComputerElite** [comment]
Songs from newer version may not work on old versions of Beat Saber

**Comment by CutieAshlynn** [comment]
ah i see thank you that very well could be the issue.

**Comment by CutieAshlynn** [comment]
is there anyway to possibly make the songs support the older versions?

**Comment by RiskiVR** [comment]
Sorry, but no. Newer DLC songs do not exist in older versions, and there is no way to force that.

**Comment by CutieAshlynn** [comment]
alright but, it confuses me how some of my dlc songs work on older versions but, the rest of them dont
