### ISSUE TITLE
Some typos. Makes the program look less professional.

### ISSUE THREAD

**Issue by Avexus02** [RiskiVR/BSLegacyLauncher#9]
![](https://cdn.discordapp.com/attachments/748704605382377574/867999251270082560/unknown.png)
Same "arguement" typo on Debug Mode and Oculus Mode, but I could not find any more than that.

**Comment by RiskiVR** [comment]
Thanks for pointing this out! I'll have that fixed on next release 💜

**Comment by RiskiVR** [comment]
Fixed in v1.3.1
